name: Compile extension

on:
  pull_request:
    paths:
      - ".github/workflows/ci-ext.*"
      - "ext/**"
      - package.xml
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci-ext.*"
      - "ext/**"
      - package.xml
    tags-ignore:
      - "**"

jobs:
  compile:
    strategy:
      matrix:
        image:
          - php:7.4-cli
          - php:8.0-cli
          - php:8.1-cli
          
    name: Image ${{ matrix.image }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull ${{ matrix.image }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker run --rm -v "$GITHUB_WORKSPACE:/app" ${{ matrix.image }} /app/.github/workflows/ci-ext.sh
